#!/bin/bash

echo -n "Répondre par oui ou non (o/n) : "
read reponse
echo "Réponse lue : $reponse"
# [ ] Permet de faire des test (les = entre 2 variables ne sont pas implémenter de base)
if [ "$reponse" = "o" ]
then
  echo "Execution du then"
else
  echo "Execution du else"
fi
